# This is free and unencumbered software released into the public domain.

name: Build Espresso.exe

on:
  create:
    ref_type: "tag"

jobs:
  build:
    runs-on: windows-2022
    steps:
      - uses: actions/checkout@v4

      - name: Install w64devkit
        run: |
          aria2c "https://github.com/skeeto/w64devkit/releases/download/v1.23.0/w64devkit-1.23.0.zip"
          7z x "w64devkit-1.23.0.zip"
          echo "$PWD\w64devkit\bin" | out-file -filepath $env:GITHUB_PATH -encoding utf8 -append

      - name: Make
        run: make

      - name: Create release
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}
        run: gh release create --latest --verify-tag ${GITHUB_REF##*/} Espresso.exe
