# This is free and unencumbered software released into the public domain.

name: Build Espresso.exe

on:
  create:
    ref_type: "tag"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install MinGW
        run: sudo apt update
           | sudo apt install -y mingw-w64

      - name: Make
        run: make CC=i686-w64-mingw32-gcc WINDRES=i686-w64-mingw32-windres

      - name: Create release
        env:
          github_token: ${{secrets.GITHUB_TOKEN}}
        run: gh release --latest --verify-tag ${GITHUB_REF##*/} Espresso.exe
