# This is free and unencumbered software released into the public domain.

name: Build Espresso.exe

on:
  create:
    ref_type: "tag"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: mingw
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: x86

      - name: build
        run: make

      - uses: ncipollo/release-action@v1
        with:
          artifacts: "Espresso.exe"
